version: "2"

services:
  data:
    image: busybox
    volumes:
      - ./services/writer:/var/www/writer
      - ./services/reader:/var/www/reader
      - ./services/images:/var/www/images
      - ./services/videos:/var/www/videos
      - ./services/files:/var/www/files
      - /var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - fpm
    volumes_from:
      - data
    ports:
      - "8080:8080"
      - "8181:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_user_name
      MYSQL_PASSWORD: my_password
      MYSQL_DATABASE: my_database
    volumes_from:
      - data
    ports:
      - "3306:3306"

  fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes_from:
      - data
    links:
      - mysql
    expose:
      - 9000
    command: php-fpm

  composer:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    entrypoint: composer
    volumes_from:
      - data
    links:
      - mysql