version: "2"

services:
  data:
    image: busybox
    volumes:
      - ./services/writer:/var/www/writer
      - ./services/reader:/var/www/reader
      - ./services/images:/var/www/images
      - ./services/videos:/var/www/videos
      - ./services/files:/var/www/files

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - fpm
    volumes_from:
      - data
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8130:8130" # writer
      - "8131:8131" # reader
      - "8132:8132" # images
      - "8133:8133" # videos
      - "8134:8134" # files
    networks:
      - page_app_network

  fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes_from:
      - data
    expose:
      - 9000
    command: php-fpm
    networks:
      - page_app_network

  composer:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    entrypoint: composer
    volumes_from:
      - data

networks:
  page_app_network:
    driver: bridge
